### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by raynamharris**
This adds a CC0 license as described in issue #2.

### CODE REVIEW

**Comment by fmichonneau** [comment]
@tracykteal where do we stand with regards to trademarking?

**Comment by gaurav** [comment]
Any progress on this?

**Comment by tracykteal** [comment]
Sorry, I don't have an update on this. We're sorting through Trademark and logo reuse policies. We'll be working on it in Quarter 3 (starting late June). If you have a specific question though, we can answer in the meantime.

**Comment by gaurav** [comment]
Cool, thanks!

**Pull request closed without merging**
